config/routes.rb
Rails.application.routes.draw do

resources :projects
resources :users
resources :sessions

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"

  root to: "projects#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :projects
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :category
  
  validates :project_name, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_secure_password
  
  validates :email, presence: true
  validates :password, presence: true
  validates :name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :city, presence: true
  validates :state, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_user

  def current_user
    User.find_by(id: session["user_id"])
  end

  def require_user
    if current_user.nil?
      redirect_to new_session_path
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :require_user, only: [:index, :show]
  
  def index
    @project = Project.all
  end

  def show
  @project = Project.find_by(id: params["id"])
  @category = @project.category
  end

  def new
    @project = Project.new
  end

  def create
    project_params = params.require(:project).permit!
    @project = Project.create(project_params)
    if @project.valid?
      redirect_to projects_path, notice: "New Project Added"
    else
      render "new"
    end
  end

  def edit
    @project = Project.find_by(id: params["id"])

  end

  def update
    project_params = params.require(:project).permit(:project_name)
    @project = Project.find_by(id: params["id"])
    @project.update(project_params)
    if @project.valid?
      redirect_to project_path
    else
      render text: "Could not update"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user

  def create
    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to root_path, notice: "Welcome!"
    else
      redirect_to root_path, alert: "Please log in."
    end

  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "Come back soon!"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user

  def create
    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to root_path, notice: "Welcome!"
    else
      redirect_to root_path, alert: "Please log in."
    end
  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "Come back soon!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
    @projects = @user.projects

  end

def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit!
    @user = User.create(user_params)
    if @user.valid?
      redirect_to users_path, notice: "New user added"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])

  end

  def update
    user_params = params.require(:user).permit(:user, :last_name)
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path
    else
      render text: "Could not update"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Buyflix</title>
    <!-- Logo Font -->
    <link href="http://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      
      <nav class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Rails equivalent to -->
          <!-- <a href="/" class="navbar-brand">Buyflix</a> -->
        
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
                <%= link_to "Projects", projects_path %>
            </li>
            <li>
                <%= link_to "Users", users_path %>
            </li>
            <li>
                <%= link_to "New Project", new_project_path %>
            </li>
             <li>
                <%= link_to "New User", new_user_path %> 
            </li>    
          </ul>
        
                  <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
                <a href="#">
                  <i class="fa fa-user"></i>
                  Hi, <%= current_user.try(:name) %>
                </a>
              <% else %>
                <%= link_to "Log In", login_path %>
              <% end %>
            </li>
            <li>
              <% if current_user %>
                <%= link_to "Log Out", logout_path %>
              <% end %>
            </li>
          </ul>

        </div>
      </nav>
    </div>
     <div class="container">
<!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>

   
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |form| %>
  <div class="form-group">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, class: "form-control" %>
  </div>
  <%= form.button 'Update Project', class: "btn btn-success" %>
  <% end %>

app/views/projects/index.html.erb
<html>
<title> Nuestro Monterrey </title>
<h1>Improve Your City</h1>



<body>

   <p class=".btn"> <% @project.each do |project| %>
   <%= link_to project.project_name, project_path(project.id) %> 

         
              <% if current_user %>
                
    <font size="1"><%= link_to "Edit", edit_project_path(project) %> <%= link_to('Delete', project_path(project), {:onclick => "return confirm('Are you sure')", method: :delete }) %>
    </font>
              <% end %>
          
   </p>
 </body>


 
<% end %>

</html>

app/views/projects/new.html.erb
<h1>New Project</h1>


<% if @project.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this project from being saved:</h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @project do |form| %>
  <div class="form-group">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: 5%>
  </div>

 <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :category_name, { include_blank: true }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, { include_blank: true }, class: "form-control" %> 
  </div>

  <%= form.button 'Create Project', class: "btn btn-success" %>
  <% end %>

app/views/projects/show.html.erb
<font color="#838B8B"> <h1> Improve your City </h1> </font>

<h3><b> Title: </b> <%= @project.project_name %></h3>
<p> <b> Description: </b> <%= @project.description %> </p>
<b> User: </b>
<%= @project.user.name %> 
<%= @project.user.last_name%>
<br>
<b> Category: </b>
<%= @project.category.category_name%> 
<br>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "form-control" %>
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>
  <%= form.button 'Update Project', class: "btn btn-success" %>
  <% end %>

app/views/users/index.html.erb
<h1>All Users</h1>


<% @users.each do |user| %>
  <li> 
    <p> <%= link_to user.name, user_path(user) %> <%= link_to user.last_name, user_path(user) %> 

              <% if current_user %>
                  <font size="1"><%= link_to "Edit", edit_user_path(user) %> <%= link_to('Delete', user_path(user), {:onclick => "return confirm('Are you sure')", method: :delete }) %>
              <% end %>

  
      
 </font>

   </font>
    </p> 
  </li>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <h6>Some errors kept this user from being saved:</h6>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <font size="1"><li><%= message %></li></font>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
      </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
      </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
    </div>

  <div class="form-group">    
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>
  <%= form.button 'Create User', class: "btn btn-success" %>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Projects</h1>


<ul>
  <p>
    <h4>
  <% @projects.each do |project| %>
  <%= link_to project.project_name, project_path(project) %> 
  </h4>
</p>
</ul>


<% end %>